# Generated by Django 4.2.29 on 2026-03-15 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lane_number', models.PositiveIntegerField(db_index=True, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('enabled_sensors', models.JSONField(default=list, help_text="List of enabled sensor positions, e.g. ['head', 'chest', 'stomach']")),
                ('primary_color', models.CharField(default='#00FF00', help_text='Primary brand color', max_length=7)),
                ('secondary_color', models.CharField(default='#000000', help_text='Secondary brand color', max_length=7)),
                ('logo_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lane', to='devices.device')),
            ],
            options={
                'verbose_name': 'Lane',
                'verbose_name_plural': 'Lanes',
                'ordering': ['lane_number'],
            },
        ),
        migrations.CreateModel(
            name='LaneScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('hit_count', models.PositiveIntegerField(default=0)),
                ('last_hit_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lane_scores', to='games.game')),
                ('lane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='lanes.lane')),
            ],
            options={
                'verbose_name': 'Lane Score',
                'verbose_name_plural': 'Lane Scores',
                'unique_together': {('lane', 'game')},
            },
        ),
    ]
