# Generated by Django 4.2.29 on 2026-03-15 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(db_index=True, max_length=36, unique=True)),
                ('mode', models.CharField(choices=[('individual', 'Individual Lane Mode'), ('all_lanes', 'All Lanes Mode')], default='individual', max_length=20)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('countdown', 'Countdown'), ('active', 'Active'), ('paused', 'Paused'), ('ended', 'Ended')], default='idle', max_length=20)),
                ('duration', models.PositiveIntegerField(default=60)),
                ('countdown_seconds', models.PositiveIntegerField(default=3)),
                ('win_score', models.PositiveIntegerField(default=1000)),
                ('use_win_score', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('duration', models.PositiveIntegerField(default=60, help_text='Game duration in seconds')),
                ('countdown_seconds', models.PositiveIntegerField(default=3, help_text='Countdown seconds before game starts')),
                ('win_score', models.PositiveIntegerField(default=1000, help_text='Score at which game ends early (optional)')),
                ('use_win_score', models.BooleanField(default=False, help_text='End game when any lane reaches win_score')),
                ('sensor_points', models.JSONField(default=dict, help_text="Points per sensor, e.g. {'head': 100, 'chest': 50}")),
                ('use_accuracy_multiplier', models.BooleanField(default=True, help_text='Multiply score by accuracy (0.0-1.0)')),
                ('enable_sound', models.BooleanField(default=True)),
                ('enable_visual_effects', models.BooleanField(default=True)),
                ('primary_color', models.CharField(default='#00FF00', max_length=7)),
                ('secondary_color', models.CharField(default='#000000', max_length=7)),
                ('logo_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Game Configuration',
                'verbose_name_plural': 'Game Configurations',
            },
        ),
        migrations.CreateModel(
            name='HitEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50)),
                ('accuracy', models.FloatField()),
                ('raw_strength', models.PositiveIntegerField(default=0)),
                ('score', models.PositiveIntegerField(default=0)),
                ('event_timestamp', models.DateTimeField(db_index=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hits', to='games.game')),
            ],
            options={
                'verbose_name': 'Hit Event',
                'verbose_name_plural': 'Hit Events',
                'ordering': ['-event_timestamp'],
            },
        ),
    ]
