# Generated by Django 4.2.29 on 2026-03-15 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        ('lanes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hitevent',
            name='lane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hit_events', to='lanes.lane'),
        ),
        migrations.AddField(
            model_name='game',
            name='active_lanes',
            field=models.ManyToManyField(blank=True, related_name='games', to='lanes.lane'),
        ),
        migrations.AddField(
            model_name='game',
            name='configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='games.gameconfiguration'),
        ),
        migrations.AddIndex(
            model_name='hitevent',
            index=models.Index(fields=['game', '-event_timestamp'], name='games_hitev_game_id_05517f_idx'),
        ),
        migrations.AddIndex(
            model_name='hitevent',
            index=models.Index(fields=['lane', '-event_timestamp'], name='games_hitev_lane_id_2d79fd_idx'),
        ),
    ]
