# Generated by Django 4.2.29 on 2026-03-15 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('serial_number', models.CharField(blank=True, default='', max_length=100)),
                ('firmware_version', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('offline', 'Offline'), ('online', 'Online'), ('registered', 'Registered'), ('error', 'Error')], default='offline', max_length=20)),
                ('is_online', models.BooleanField(default=False)),
                ('supported_sensors', models.JSONField(default=list, help_text="List of sensor positions, e.g. ['head', 'chest', 'stomach']")),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('channel_name', models.CharField(blank=True, default='', max_length=200)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'ordering': ['device_id'],
            },
        ),
        migrations.CreateModel(
            name='DeviceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], default='INFO', max_length=10)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='devices.device')),
            ],
            options={
                'verbose_name': 'Device Log',
                'verbose_name_plural': 'Device Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['device', '-timestamp'], name='devices_dev_device__b10ac7_idx')],
            },
        ),
    ]
